name: Deploy to Selectel

on:
  push:
    branches:
      - main   # деплой при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Deploy to Selectel Object Storage
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.SELECTEL_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SELECTEL_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SELECTEL_SECRET_KEY }}
          AWS_REGION: ru-1
          AWS_ENDPOINT: ${{ secrets.SELECTEL_ENDPOINT }}
          SOURCE_DIR: ./out
