- name: Deploy to Selectel Object Storage
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.SELECTEL_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.SELECTEL_SECRET_KEY }}
  run: |
    echo "Содержимое текущей папки:"
    ls -la

    if [ ! -d ./out ]; then
      echo "Ошибка: папка ./out не найдена!"
      exit 1
    fi

    echo "Устанавливаем awscli через pip"
    python3 -m pip install --upgrade pip awscli

    echo "Проверяем версию awscli"
    aws --version

    echo "Синхронизация ./out в бакет Selectel"
    aws s3 sync ./out s3://${{ secrets.SELECTEL_BUCKET }} \
      --endpoint-url "${{ secrets.SELECTEL_ENDPOINT }}" \
      --delete \
      --acl public-read \
      --exact-timestamps \
      --debug
