name: Build and Deploy to Selectel

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          # если build не создал ./out, пробуем выполнить next export
          if [ ! -d ./out ]; then
            npm run export || echo "No export script found"
          fi

      - name: Deploy to Selectel Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SELECTEL_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SELECTEL_SECRET_KEY }}
        run: |
          if [ ! -d ./out ]; then
            echo "Error: ./out not found. Build failed."
            exit 1
          fi

          # ставим awscli через pip, потому что в ubuntu-24.04 через apt его нет
          python3 -m pip install --upgrade pip awscli

          # синхронизируем сайт
          aws s3 sync ./out s3://${{ secrets.SELECTEL_BUCKET }} \
            --endpoint-url "${{ secrets.SELECTEL_ENDPOINT }}" \
            --delete \
            --acl public-read
